replicaCount: 3
image:
  repository: 695418593935.dkr.ecr.ap-southeast-2.amazonaws.com/gitops-platform-aws-app-dev
  tag: 41b51941f48a152af48512e5fa2bf0ba5d6b52c8
service:
  type: LoadBalancer
  port: 80
