name: Build and Release Application

on:
  workflow_dispatch:
  env:
    AWS_REGION: ap-southeast-2
    AWS_ACCOUNT_ID: 695418593935
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::695418593935:role/gitops-platform-aws-github-actions-role-dev
      - run: |
          docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gitops-platform-aws-app-dev:${{ github.sha }} .
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gitops-platform-aws-app-dev:${{ github.sha}}
      - run: |
          cd helm/demo-app
          yq e -i ".image.tag = \"${{ github.sha }}\"" values.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin HEAD:main
